service: aws-lambda-app
#ref: https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1

functions:
  http:
    handler: handler.http
    events:
      - http:
          path: /
          method: any
          cors: true

      - http:
          path: /{any+}
          method: any
          cors: true

package:
  exclude:
    - '.gitignore'
    - '*.json'
    - '*.ts'
    - '*.yml'
    - '*.md'
    - '*.xml'
    - '*.spec.js'
    - '*.config.js'
    - 'test-report.html'
    - 'coverage/**'
    - '.idea/**'
    - 'reports/**'
    - 'coverage.svg'

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.compliment.it
    basePath: 'compliment-it'
    stage: ${self:provider.stage}
    createRoute53Record: false