# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run tslint

      - run:
          name: Run Tests
          command: npm run test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: reports

      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

      - run:
          name: Create code coverage badge
          command: npm run coverage-badge
          when: always

      - store_artifacts:
          path: coverage.svg
          destination: coverage.svg

      - run:
          name: Deploy to AWS
          command: npm run compile-deploy
