# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: timbru31/java-node:alpine

    working_directory: ~/

    steps:
      - checkout

      - run: pwd

      - run: ll

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "~/compliment-it-ui/package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - ~/compliment-it-ui/node_modules
          key: v1-dependencies-{{ checksum "~/compliment-it-ui/package.json" }}
        
      # run tests!
      - run: npm test
